version: 3.1.0.{build}
skip_tags: true
configuration: Release
init:
- git config --global core.autocrlf true
install:
- ps: npm install -g markdownlint-cli
build:
  publish_nuget: true
  verbosity: minimal
environment:
  Test.Path: C:\projects\html2markdown\test\Html2Markdown.Test\Files\
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
  api_key:
    secure: mqfd5QXj3a2N+D2EP9avxupQJRBJFEKT9kjF7Tipl1OCkUvPBsKjfiZMQHpnwVKq
deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key; if ($lastexitcode -ne 0) {throw}}
build_script:
  - cmd: >-
      cd %BUILD_DIR%

      markdownlint .

      dotnet restore
      
      dotnet build

      dotnet pack .\src\Html2Markdown\Html2Markdown.csproj -c %CONFIGURATION% /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
test_script:
  - cmd: >-
      dotnet test .\test\Html2Markdown.Test\Html2Markdown.Test.csproj --logger "trx;LogFileName=results.trx"
after_test:
  - ps: ./uploadTestResults.ps1
  - ps: ./pushDocumentation.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:appveyor_repo_branch
artifacts:
- path: src\Html2Markdown\bin\Release\*.nupkg
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'